In [1]:
import cv2
import numpy as np
import glob

read and show image
------------


In [ ]:
img1=cv2.imread("img/img1.jpeg") 
# read the image 
img2=cv2.imread("img/img2.jpeg")
#resize image
re_img01=cv2.resize(img1,(500,800))
# cv2.imshow("madhu",img1)
cv2.imshow("madhu2",img2)
cv2.imshow("madhu3",re_img01)
print(len(img1))
print(img1.shape)
print(img1)
print(img1[0])

cv2.waitKey(5000) #if we pwwwress any key then only it will close the window otherwise we need to pass time which is in milisecond
cv2.destroyAllWindows()



598
(598, 400, 3)
[[100  87  43]
 [100  87  43]
 [100  87  43]
 ...
 [ 79 148 218]
 [ 79 148 218]
 [ 78 147 217]]


USING NUMPY ALSO TO WORK ON IMAGES ....img also return a arrey as rgb value

In [3]:
img3=cv2.imread("img/img1.jpeg")
re_img=cv2.resize(img3,(200,200))
# horizontally concetation of two image in a single frame 
h=np.hstack((re_img,re_img,re_img))
v=np.vstack((re_img,re_img,re_img))
sq=np.vstack((h,h,h))
vq=np.hstack((v,v,v))
vq02=np.hstack((h,h,h))
cv2.imshow("madhu02",h)
cv2.imshow("madhu03",v)
cv2.imshow("madhu04",sq)
cv2.imshow("madhu05",vq)
cv2.imshow("madhu06",vq02)
cv2.waitKey(0)
cv2.destroyAllWindows()



lets create a slide show of images 
----------------------

In [4]:
# list of images avalilable in img diretory
image_list = glob.glob("img/**/*.*", recursive=True)
            
print(image_list)

for img_path in image_list:
    image = cv2.imread(img_path)
    cv2.imshow("Image", image)
    cv2.waitKey(500)  # Display each image for 500ms
cv2.destroyAllWindows()

['img\\d1.jpeg', 'img\\d2.jpeg', 'img\\h1.jpeg', 'img\\h2.jpeg', 'img\\img1.jpeg', 'img\\img2.jpeg', 'img\\img3.jpeg', 'img\\img4bw.jpeg', 'img\\img5.jpeg', 'img\\img6.jpeg']


channel


In [ ]:
img=cv2.imread("img/img6.jpeg",1) 
img01=cv2.imread("img/img6.jpeg",-1) 
img02=cv2.imread("img/img6.jpeg",0) 
print(img.shape)
print(img01.shape)
print(img02.shape)
cv2.imshow("tab01",img)
cv2.imshow("tab02",img01)
cv2.imshow("tab03",img02)
cv2.waitKey(10)
cv2.destroyAllWindows()
img=cv2.resize(img,(500,500))

(600, 400, 3)
(600, 400, 3)
(600, 400)


WRITE TEXT OVER IMAGE 

In [ ]:
import cv2

# Read the image
img02 = cv2.imread("img/img6.jpeg")

# Check if the image is loaded correctly
if img02 is None:
    print("Error: Image not found or cannot be loaded.")
else:
    # Add text to the image
    txt=cv2.putText(
        img02, "madhujya", (50, 250),
        cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 
        3, (0, 234, 203), 3, cv2.LINE_AA,
    )
    txt2=cv2.putText(
        img02, "madhujya", (50, 260),
        cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 
        3, (30, 124, 103), 3, cv2.LINE_AA,
        bottomLeftOrigin=True
    )

    # Display the image
    cv2.imshow("tab02", txt)
    cv2.waitKey(10)
    cv2.destroyAllWindows()


In [ ]:
gray_image = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
cv2.imshow("Grayscale Image", gray_image)
cv2.imwrite("new_image.jpg", gray_image)

cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:

# Create a blank black image
image = np.zeros((500, 500, 3), dtype="uint8")

# Draw a red line
cv2.line(image, (50, 50), (400, 50), (0, 0, 255), 2)

# Draw a green rectangle
cv2.rectangle(image, (50, 100), (400, 200), (0, 255, 0), 2)

# Draw a blue circle
cv2.circle(image, (250, 300), 50, (255, 0, 0), -1)

# Add text
cv2.putText(image, "OpenCV Shapes", (100, 450), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

cv2.imshow("Shapes", image)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:

# Define colors in BGR format
blue = np.zeros((500, 500, 3), dtype="uint8")
blue[:] = (255, 0, 0)  # Blue color

green = np.zeros((500, 500, 3), dtype="uint8")
green[:] = (0, 255, 0)  # Green color

red = np.zeros((500, 500, 3), dtype="uint8")
red[:] = (0, 0, 255)  # Red color

yellow = np.zeros((500, 500, 3), dtype="uint8")
yellow[:] = (0, 255, 255)  # Yellow color

cyan = np.zeros((500, 500, 3), dtype="uint8")
cyan[:] = (255, 255, 0)  # Cyan color

magenta = np.zeros((500, 500, 3), dtype="uint8")
magenta[:] = (255, 0, 255)  # Magenta color

# Show images one by one
cv2.imshow("Blue", blue)
cv2.imshow("Green", green)
cv2.imshow("Red", red)
cv2.imshow("Yellow", yellow)
cv2.imshow("Cyan", cyan)
cv2.imshow("Magenta", magenta)

cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
gradient = np.zeros((500, 500, 3), dtype="uint8")

for i in range(500):
    gradient[:, i] = (i // 2, i // 2, 255 - i // 2)  # Creating a gradient effect

cv2.imshow("Gradient", gradient)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
palette = np.zeros((300, 900, 3), dtype="uint8")

# Divide into three sections for RGB
palette[:, 0:300] = (255, 0, 0)  # blue
palette[:, 300:600] = (0, 255, 0)  # Green
palette[:, 600:900] = (0, 0, 255)  # red

cv2.imshow("RGB Palette", palette)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np



# Load image in grayscale
image = cv2.imread("img/img3.jpeg", cv2.IMREAD_GRAYSCALE)

# Convert to binary image using thresholding
_, binary = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)

# Find contours
contours, hierarchy = cv2.findContours(binary, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# Draw contours on a blank image
result = np.zeros((image.shape[0], image.shape[1], 3), dtype=np.uint8)
result[:] = (60, 123, 10)
cv2.drawContours(result, contours, -1, (0, 255, 0), 2)

# Display the image
cv2.imshow("Contours", result)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

# Load main image and template in grayscale
image = cv2.imread("cartoon.jpg", cv2.IMREAD_GRAYSCALE)
template = cv2.imread("cartoon.jpg", cv2.IMREAD_GRAYSCALE)

# Get width and height of the template
h, w = template.shape

# Perform template matching
result = cv2.matchTemplate(image, template, cv2.TM_CCOEFF_NORMED)

# Get the best match location
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)

# Top-left corner of matched region
top_left = max_loc  

# Bottom-right corner
bottom_right = (top_left[0] + w, top_left[1] + h)

# Draw a rectangle around the detected area
cv2.rectangle(image, top_left, bottom_right, (255, 250, 250), 2)

# Show the result
cv2.imshow("Detected", image)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

# Load the image
image = cv2.imread("img/img2.jpeg", cv2.IMREAD_GRAYSCALE)

# Apply Canny edge detection
edges = cv2.Canny(image, 100, 200)

# Show the result
cv2.imshow("Canny Edge Detection", edges)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

# Load the image
image = cv2.imread("img/img5.jpeg")

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply thresholding (convert image to binary)
_, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY_INV)
edges = cv2.Canny(image, 100, 200)
# Find contours
contours, hierarchy = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# Draw contours on the original image
cv2.drawContours(image, contours, -1, (0, 255, 0), 2)

# Display the number of objects
print(f"Number of objects detected: {len(contours)}")

# Show images
cv2.imshow("Binary Image", binary)
cv2.imshow("Contours", image)
cv2.waitKey(10)
cv2.destroyAllWindows()


Number of objects detected: 4268


In [ ]:
import cv2
import numpy as np

# Load an image
image = cv2.imread("img/img3.jpeg")

# Apply Gaussian Blur
blurred = cv2.GaussianBlur(image, (5, 5), 0)

# Show the images
cv2.imshow("Original Image", image)
cv2.imshow("Gaussian Blurred Image", blurred)
cv2.waitKey(10)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np

# Load an image
image = cv2.imread("img/img3.jpeg", 0)
_, binary = cv2.threshold(image, 150, 255, cv2.THRESH_BINARY_INV)
# Create a 3x3 kernel
kernel = np.ones((3, 3), np.uint8)

# Apply erosion
eroded = cv2.erode(binary, kernel, iterations=1)
dilutte=cv2.dilate(binary,kernel, iterations=1)
# Show images
cv2.imshow("Original", image)
cv2.imshow("binary", binary)
cv2.imshow("Eroded", eroded)
cv2.imshow("d", dilutte)
cv2.waitKey(10)
cv2.destroyAllWindows()
