In [1]:
import cv2
import numpy as np

# Create a blank black image
image = np.zeros((500, 500, 3), dtype=np.uint8)

# 1. Draw a Line
cv2.line(image, (50, 50), (450, 50), (0, 255, 0), thickness=3)

# 2. Draw a Rectangle
cv2.rectangle(image, (100, 100), (400, 200), (255, 0, 0), thickness=3)

# 3. Draw a Circle
cv2.circle(image, (250, 350), 50, (0, 0, 255), thickness=3)

# 4. Draw an Ellipse
cv2.ellipse(image, (250, 250), (100, 50), 60, 45, 90, (255, 255, 0), thickness=3)

# 5. Draw a Polygon
points = np.array([[150, 400], [200, 300], [300, 300], [350, 400]], np.int32)
points = points.reshape((-1, 1, 2))
print(points)
cv2.polylines(image, [points], isClosed=True, color=(0, 255, 255), thickness=3)

# Display the image
cv2.imshow("Shapes", image)


# Load the image
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply thresholding
_, binary = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)

# Find contours
contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Iterate through contours
for i, contour in enumerate(contours):
    area = cv2.contourArea(contour)  # Calculate area
    points = len(contour)            # Number of points in the contour
    
    # Draw contour
    cv2.drawContours(image, [contour], -1, (0, 255, 0), 2)
    
    # Display contour number and area
    x, y, w, h = cv2.boundingRect(contour)
    cv2.putText(image, f"ID:{i} Area:{int(area)}", (x, y - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2)

    print(f"Contour {i}: Points={points}, Area={area}")

# Show image with detected contours
cv2.imshow("Contours", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.waitKey(0)
cv2.destroyAllWindows()


[[[150 400]]

 [[200 300]]

 [[300 300]]

 [[350 400]]]
Contour 0: Points=244, Area=16182.5


here I have used setMouseCallback 
===================
i the following exaple when i click left button it create a green dot or circle
when i click right button it create or draw a red button

In [ ]:
import cv2
import numpy as np

# Callback function for mouse events
def draw_circle(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img, (x, y), 10, (0, 255, 0), -1)  # Green for left click
    elif event == cv2.EVENT_RBUTTONDOWN:
        cv2.circle(img, (x, y), 10, (0, 0, 255), -1)  # Red for right click


# Create a black image and bind the function
img = np.zeros((512, 512, 3), np.uint8)
cv2.namedWindow('image')
cv2.setMouseCallback('image', draw_circle)

while True:
    cv2.imshow('image', img)
    if cv2.waitKey(20) & 0xFF == 27:  # Press 'Esc' to exit
        break

cv2.destroyAllWindows()


In [28]:
import cv2

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(frame, contours, -1, (0, 255, 0), 2)
    
    cv2.imshow("Webcam Object Detection", frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


In [29]:


# Create a blank image
blank = np.zeros((500, 500), dtype=np.uint8)
image2 = np.zeros((500, 500), dtype=np.uint8)

# Draw a rectangle on image1
rec=cv2.rectangle(blank.copy(), (30, 30), (370, 370), 255, -1)

# Draw a circle on image2
cir=cv2.circle(blank.copy(), (200, 200), 200, 255, -1)

# Perform bitwise AND (Intersection of shapes)
bitwise_and = cv2.bitwise_and(rec, cir)

# Perform bitwise OR (Union of shapes)
bitwise_or = cv2.bitwise_or(rec, cir)

# Perform bitwise XOR (Exclusive regions)
bitwise_xor = cv2.bitwise_xor(rec, cir)

# Perform bitwise NOT (Inverse of one shape)
bitwise_not = cv2.bitwise_not(rec)

# Display results
cv2.imshow("Rectangle", rec)
cv2.imshow("Circle", cir)
cv2.imshow("Bitwise AND (Intersection)", bitwise_and)
cv2.imshow("Bitwise OR (Union)", bitwise_or)
cv2.imshow("Bitwise XOR (Exclusive)", bitwise_xor)
cv2.imshow("Bitwise NOT (Inversion)", bitwise_not)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [30]:


# Create a blank image
image = np.zeros((500, 500, 3), dtype=np.uint8)

# Define points of the polygon
pts = np.array([[100, 100], [200, 50], [300, 100], [250, 200], [150, 200]], np.int32)
pts = pts.reshape((-1, 1, 2))

# Draw filled polygon
cv2.fillPoly(image, [pts], (0, 255, 0))

cv2.imshow("Polygon", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


Draw A curve 

In [31]:


# Function to compute Bezier point
def bezier_curve(t, p0, p1, p2, p3):
    u = 1 - t
    return (u**3) * p0 + (3 * u**2 * t) * p1 + (3 * u * t**2) * p2 + (t**3) * p3

# Create a blank image
image = np.zeros((500, 500, 3), dtype=np.uint8)

# Control points
p0 = np.array([100, 300])
p1 = np.array([200, 100])
p2 = np.array([300, 100])
p3 = np.array([400, 300])

# Generate Bezier curve points
curve = np.array([bezier_curve(t, p0, p1, p2, p3) for t in np.linspace(0, 1, 100)], dtype=np.int32)

# Draw the curve
cv2.polylines(image, [curve], isClosed=False, color=(255, 0, 0), thickness=2)

cv2.imshow("Bezier Curve", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [34]:

# Create a blank image
image = np.zeros((500, 500, 3), dtype=np.uint8)

# Define rotated rectangle
rect = ((250, 250), (200, 100), 30)  # Center, (width, height), angle
box = cv2.boxPoints(rect)
box = np.int32(box)

# Draw the rectangle
cv2.polylines(image, [box], isClosed=True, color=(0, 0, 255), thickness=2)

cv2.imshow("Rotated Rectangle", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [35]:


# Create a blank image
image = np.zeros((500, 500, 3), dtype=np.uint8)

# Star coordinates
star_pts = np.array([[270, 150], [350, 150], [280, 200], 
                     [300, 300], [250, 230], [200, 300], [220, 200], 
                     [150, 150], [230, 150],[250, 50]], np.int32)

star_pts = star_pts.reshape((-1, 1, 2))

# Draw the star
cv2.polylines(image, [star_pts], isClosed=True, color=(0, 255, 255), thickness=2)

cv2.imshow("Star", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
